version: "3.8"

services:

  tfm:
    restart: always
    image: "python:3.10-slim"
    hostname: "tfm"
    env_file:
      - .env
    build:
      context: .
      dockerfile: ./docker/python/Dockerfile
    volumes:
      - ./:/app:rw
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    tty: true
    depends_on:
      crimebb:
        condition: service_healthy

  crimebb:
    hostname: "crimebb"
    restart: "always"
    image: "postgres:13.4-buster"
    build:
      context: "."
      dockerfile: ./docker/postgres_crimebb/Dockerfile
    env_file:
      - .env
    volumes:
      - "./postgres-data/:/var/lib/postgresql/data/:rw"
      - "../crimeBB/:/dumps:ro"
    ports:
      - "5432:5432"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
