version: "3.8"

services:

  crimebb:
    hostname: "crimebb"
    restart: "always"
    image: "postgres:13.4-buster"
    build:
      context: "."
      dockerfile: ./docker/postgres_crimebb/Dockerfile
    env_file:
      - ./docker/postgres_crimebb/.env
    volumes:
      - "./postgres-data/:/var/lib/postgresql/data/:rw"
      - "../dumps_crimebb/:/dumps:ro"
    ports:
      - "5432:5432"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
